---
auth_mode: basic # basic, oauth
basic_auth:
    user: username
    password: password
oauth:
    consumer_key: key
    consumer_secret: secret
    request_token:
    request_secret:
update_every: 5 # minutes
